#! /bin/bash

# MX Tour for MX Linux 21 Xfce
# 
# Hastily put together Tour Guide application for MX Linux 21 Xfce.

# set some stuff up
KEY=$$


# Intro tab
cat /usr/share/mx-tour/text/tour-intro |\
	yad --plug=$KEY --tabnum=1 --text=$"Intro" \
		--text="<b>WELCOME TO THE MX LINUX TOUR</b>" --text-align=center \
		--text-info --wrap --margins=5 &

# Panel tab
cat /usr/share/mx-tour/text/panel |\
	yad --plug=$KEY --tabnum=2 \
		--image=/usr/share/mx-tour/images/panel.png \
		--text-info --wrap --margins=5 &
		
# Whisker Menu tab
cat /usr/share/mx-tour/text/whisker-menu |\
	yad --plug=$KEY --tabnum=3 \
		--image=/usr/share/mx-tour/images/whisker-menu.png \
		--text-info --wrap --margins=5 &

# Docklike tab
cat /usr/share/mx-tour/text/docklike |\
	yad --plug=$KEY --tabnum=4 \
		--image=/usr/share/mx-tour/images/docklike.png --image-on-top \
		--text-info --wrap --margins=5 &

# Conky tab
cat /usr/share/mx-tour/text/conky |\
	yad --plug=$KEY --tabnum=5 \
		--image=/usr/share/mx-tour/images/conky.png --image-on-top \
		--text-info --wrap --margins=5 &

# MX Tools tab
cat /usr/share/mx-tour/text/mx-tools |\
	yad --plug=$KEY --tabnum=6 \
		--image=/usr/share/mx-tour/images/mx-tools.png --image-on-top \
		--text-info --quoted-output --wrap --margins=5 & \

# MX Welcome tab
cat /usr/share/mx-tour/text/mx-welcome |\
	yad --plug=$KEY --tabnum=7 \
		--image=/usr/share/mx-tour/images/mx-welcome.png --image-on-top \
		--text-info --quoted-output --wrap --margins=5 &

# MX Tweak tab
cat /usr/share/mx-tour/text/mx-tweak |\
	yad --plug=$KEY --tabnum=8 \
		--image=/usr/share/mx-tour/images/mx-tweak.png --image-on-top \
		--text-info --quoted-output --wrap --margins=5 &

# Install Apps tab
cat /usr/share/mx-tour/text/mxpi |\
	yad --plug=$KEY --tabnum=9 \
		--image=/usr/share/mx-tour/images/mxpi.png --image-on-top \
		--text-info --quoted-output --wrap --margins=5 & \

# MX Updater tab
cat /usr/share/mx-tour/text/mx-updater |\
	yad --plug=$KEY --tabnum=10 \
		--image=/usr/share/mx-tour/images/mx-updater.png --image-on-top \
		--text-info --quoted-output --wrap --margins=5 &

# MX Snapshot tab
cat /usr/share/mx-tour/text/mx-snapshot |\
	yad --plug=$KEY --tabnum=11 \
		--image=/usr/share/mx-tour/images/mx-snapshot.png --image-on-top \
		--text-info --quoted-output --wrap --margins=5 &

# Timeshift tab
cat /usr/share/mx-tour/text/timeshift |\
	yad --plug=$KEY --tabnum=12 \
		--image=/usr/share/mx-tour/images/timeshift.png --image-on-top \
		--text-info --quoted-output --wrap --margins=5 &

# QSI tab
cat /usr/share/mx-tour/text/qsi |\
	yad --plug=$KEY --tabnum=13 \
		--image=/usr/share/mx-tour/images/qsi.png --image-on-top \
		--text-info --quoted-output --wrap --margins=5 &

# Get Help tab
	yad --plug=$KEY --tabnum=14 --image=help-browser --text=$"Get Help" \
		--text="<b>There are many resources to get help</b>" --text-align=center &


# main dialog
yad --notebook --width=1024 --height=800 --fixed --center \
	--stack \
	--title="MX Tour" \
	--window-icon=usr/share/icons/hicolor/scalable/apps/mx-tour.svg \
	--button="Close" \
	--button="Previous" \
	--button="Next" \
	--key=$KEY --tab-pos=left \
	--tab="Intro" \
	--tab="Panel" \
	--tab="Whisker Menu" \
	--tab="Taskbar" \
	--tab="Conky" \
	--tab="MX Tools" \
	--tab="MX Welcome"  \
	--tab="MX Tweak"  \
	--tab="Install Apps" \
	--tab="Updating" \
	--tab="MX Snapshot" \
	--tab="Timeshift" \
	--tab="System Info" \
	--tab="Get Help" \
	--active-tab=${1:-1}

exit 0
